title: Army Logistics
description: A knowledge hub for U.S. Army logistics
theme: just-the-docs

url: https://armylog.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
